### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [dakotabryant/splurtyapp#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by dakotabryant** [comment]
Ken, I've gone ahead and added the viewport tag. Pushed it to Github/Heroku, and tested on my phone. Looks much better! Thanks for the heads up.

**Comment by kenmazaika** [comment]
Thumbs up, Dakota.  Keep up the awesome work coding! :+1:
